package modelo.basico;

/* !!NÃO UTILIZADO NO PROJETO!!
 * INTERFACE MARCADORA
 * NÃO GERA REGRA DE IMPLEMENTAÇÃO DE MÉTODOS
 * PORÉM SERVE PARA MARCAR CLASSES CONVENIENTES 
 * QUE IRÃO IMPLEMENTAR O DAO...
 * OU SEJA, NO DAO TEREMOS:
 * 		public class DAO<E extends Entidade>
 * E NAS CLASSES QUE FARÃO PARTE DA ESTRUTURA
 * DO BANCO TEREMOS:
 * 		public class Produto implements Entidade
 * RESUMINDO: ESSA INTERFACE SERVE APENAS COMO 
 * MARCADOR PARA AQUELAS CLASSES QUE SERÃO 
 * PERSISTIDAS NO BANCO. 
 * */
public interface Entidade {
	
}
